# Stenozaznamy

In [1]:
import sys, os
sys.path.insert(0, os.path.abspath('../..'))

In [2]:
from datetime import datetime

In [3]:
from parlamentikon.Snemovna import *
from parlamentikon.Stenozaznamy import *
from parlamentikon.utility import *

## Tabulka Steno

In [4]:
s = Steno()
s.head()

2021-03-19:13:59:34 INFO     [utility.py:21] Stahuji 'https://www.psp.cz/eknih/cdrom/opendata/poslanci.zip'.
2021-03-19:13:59:35 INFO     [utility.py:21] Stahuji 'https://www.psp.cz/eknih/cdrom/opendata/steno.zip'.

,id_steno,id_organ,schuze,turn,od_steno,jd,od_t,do_t
49626,115470,172,1,1,2017-11-20 00:00:00+01:00,1,780,790
49627,115471,172,1,2,2017-11-20 00:00:00+01:00,1,790,800
49628,115472,172,1,3,2017-11-20 00:00:00+01:00,1,800,810
49629,115473,172,1,4,2017-11-20 00:00:00+01:00,1,810,820
49630,115474,172,1,5,2017-11-20 00:00:00+01:00,1,820,830

In [5]:
s.popis()

Počet řádků v tabulce: 10140

Sloupce s jedinou hodnotou:
  'id_organ' má všude hodnotu '172'

Nulové hodnoty:
Tabulka neobsahuje žádné nulové hodnoty [NaNy atp.]

,počet unikátních hodnot,počet nenulových hodnot,typ,tabulka,vlastni,popis
id_steno,10140,10140,Int64,steno,False,Identifikátor stenozáznamu
id_organ,1,10140,Int64,steno,False,Identifikátor orgánu stenozáznamu (v případě P...
schuze,90,10140,Int64,steno,False,Číslo schůze.
turn,456,10140,Int64,steno,False,Číslo stenozáznamu (turn). Pokud číselná řada ...
od_steno,268,10140,"datetime64[ns, Europe/Prague]",steno,False,Datum začátku stenozáznamu.
jd,12,10140,Int64,steno,False,Číslo jednacího dne v rámci schůze (používá se...
od_t,274,10140,Int64,steno,False,Čas začátku stenozáznamu v minutách od začátku...
do_t,484,10140,Int64,steno,False,Čas konce stenozáznamu v minutách od začátku k...

## Tabulka StenoBod

In [6]:
sb = StenoBod()
sb.tail()

2021-03-19:13:59:38 INFO     [utility.py:21] Stahuji 'https://www.psp.cz/eknih/cdrom/opendata/poslanci.zip'.
2021-03-19:13:59:39 INFO     [utility.py:21] Stahuji 'https://www.psp.cz/eknih/cdrom/opendata/steno.zip'.

,id_steno,aname,id_bod,id_organ,schuze,turn,od_steno,jd,od_t,do_t
20957,126107,784,44627,172,87,234,2021-03-11 00:00:00+01:00,7,670,680
20958,126109,789,44628,172,87,237,2021-03-11 00:00:00+01:00,7,700,710
20959,126119,811,44523,172,87,246,2021-03-11 00:00:00+01:00,7,870,880
20960,126140,932,44360,172,87,269,2021-03-12 00:00:00+01:00,8,560,562
20961,126158,959,44363,172,87,287,2021-03-12 00:00:00+01:00,8,790,800

In [7]:
sb.popis()

Počet řádků v tabulce: 2105

Sloupce s jedinou hodnotou:
  'id_organ' má všude hodnotu '172'

Nulové hodnoty:
Tabulka neobsahuje žádné nulové hodnoty [NaNy atp.]

,počet unikátních hodnot,počet nenulových hodnot,typ,tabulka,vlastni,popis
id_steno,1703,2105,Int64,steno_bod,False,"Identifikátor stenozáznamu, viz steno:id_steno."
aname,1088,2105,Int64,steno_bod,False,Pozice v indexu jednacího dne.
id_bod,1716,2105,Int64,steno_bod,False,"Identifikace bodu pořadu schůze, viz bod_schuz..."
id_organ,1,2105,Int64,steno,False,Identifikátor orgánu stenozáznamu (v případě P...
schuze,77,2105,Int64,steno,False,Číslo schůze.
turn,421,2105,Int64,steno,False,Číslo stenozáznamu (turn). Pokud číselná řada ...
od_steno,259,2105,"datetime64[ns, Europe/Prague]",steno,False,Datum začátku stenozáznamu.
jd,12,2105,Int64,steno,False,Číslo jednacího dne v rámci schůze (používá se...
od_t,148,2105,Int64,steno,False,Čas začátku stenozáznamu v minutách od začátku...
do_t,156,2105,Int64,steno,False,Čas konce stenozáznamu v minutách od začátku k...

## Tabulka StenoRecnici

In [8]:
sr = StenoRecnici()
sr.tail()

2021-03-19:13:59:41 INFO     [utility.py:21] Stahuji 'https://www.psp.cz/eknih/cdrom/opendata/poslanci.zip'.
2021-03-19:13:59:43 INFO     [utility.py:21] Stahuji 'https://www.psp.cz/eknih/cdrom/opendata/steno.zip'.

,id_steno,id_osoba,aname,id_bod,druh__ORIG,druh,id_organ,schuze,turn,od_steno,...,do_t,pred,prijmeni,jmeno,za,narozeni,pohlavi__ORIG,zmena,umrti,pohlavi
71138,126162,6531,1,44363,4,předsedající,172,87,290,2021-03-12 00:00:00+01:00,...,827,Bc.,Pikal,Vojtěch,,1987-02-19 00:00:00+01:00,M,NaT,NaT,muž
71139,126162,6531,3,44363,4,předsedající,172,87,290,2021-03-12 00:00:00+01:00,...,827,Bc.,Pikal,Vojtěch,,1987-02-19 00:00:00+01:00,M,NaT,NaT,muž
71140,126162,6531,5,44363,4,předsedající,172,87,290,2021-03-12 00:00:00+01:00,...,827,Bc.,Pikal,Vojtěch,,1987-02-19 00:00:00+01:00,M,NaT,NaT,muž
71141,126162,6531,7,44363,4,předsedající,172,87,290,2021-03-12 00:00:00+01:00,...,827,Bc.,Pikal,Vojtěch,,1987-02-19 00:00:00+01:00,M,NaT,NaT,muž
71142,126162,6531,9,44363,4,předsedající,172,87,290,2021-03-12 00:00:00+01:00,...,827,Bc.,Pikal,Vojtěch,,1987-02-19 00:00:00+01:00,M,NaT,NaT,muž

In [9]:
sr.popis()

Počet řádků v tabulce: 71143

Sloupce s jedinou hodnotou:
  'id_organ' má všude hodnotu '172'

Nulové hodnoty:
Sloupec 'id_bod' obsahuje 14.41% (10250 z 71143) nulových hodnot (např. NaNů).
Sloupec 'narozeni' obsahuje 0.24% (171 z 71143) nulových hodnot (např. NaNů).
Sloupec 'zmena' obsahuje 86.91% (61827 z 71143) nulových hodnot (např. NaNů).
Sloupec 'umrti' obsahuje 100.00% (71143 z 71143) nulových hodnot (např. NaNů).

,počet unikátních hodnot,počet nenulových hodnot,typ,tabulka,vlastni,popis
id_steno,9361,71143,Int64,steno_recnici,False,"Identifikátor stenozáznamu, viz Steno:id_steno."
id_osoba,293,71143,Int64,steno_recnici,False,"Identifikátor osoby, viz Osoby:id_osoba."
aname,40,71143,Int64,steno_recnici,False,Identifikace vystoupení v rámci stenozáznamu.
id_bod,1697,60893,Int64,steno_recnici,False,"Identifikace bodu pořadu schůze, viz bod_schuz..."
druh__ORIG,5,71143,Int64,steno_recnici,False,"Druh vystoupení řečníka: 0 či null - neznámo, ..."
druh,5,71143,string,steno_recnici,True,Druh vystoupení řečníka.
id_organ,1,71143,Int64,steno,False,Identifikátor orgánu stenozáznamu (v případě P...
schuze,90,71143,Int64,steno,False,Číslo schůze.
turn,456,71143,Int64,steno,False,Číslo stenozáznamu (turn). Pokud číselná řada ...
od_steno,268,71143,"datetime64[ns, Europe/Prague]",steno,False,Datum začátku stenozáznamu.
jd,12,71143,Int64,steno,False,Číslo jednacího dne v rámci schůze (používá se...
od_t,271,71143,Int64,steno,False,Čas začátku stenozáznamu v minutách od začátku...
do_t,478,71143,Int64,steno,False,Čas konce stenozáznamu v minutách od začátku k...
pred,36,71143,string,osoby,False,Titul pred jmenem
prijmeni,285,71143,string,osoby,False,"Příjmení, v některých případech obsahuje i dod..."
jmeno,108,71143,string,osoby,False,Jméno
za,19,71143,string,osoby,False,Titul za jménem
narozeni,253,70972,"datetime64[ns, Europe/Prague]",osoby,False,"Datum narození, pokud neznámo, pak 1.1.1900."
pohlavi__ORIG,3,71143,string,osoby,False,"Pohlaví, ""M"" jako muž, ostatní hodnoty žena"
zmena,5,9316,"datetime64[ns, Europe/Prague]",osoby,False,Datum posledni změny
umrti,0,0,"datetime64[ns, Europe/Prague]",osoby,False,Datum úmrtí
pohlavi,2,71143,string,osoby,True,Pohlaví.

In [10]:
print(f"Poslední běh notebooku dokončen {datetime.now().strftime('%d.%m.%Y v %H:%M:%S')}.")

Poslední běh notebooku dokončen 19.03.2021 v 13:59:47.